# Generated by Django 5.1.11 on 2025-11-04 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_ftpclient"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador de organización"),
                    ("MANAGER", "Gerente"),
                    ("STORE_USER", "Usuario de tienda"),
                    ("VIEWER", "Solo lectura"),
                ],
                default="STORE_USER",
                help_text="Rol del usuario dentro de su organización",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la organización",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Identificador único de URL para la organización",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Si la organización está activa"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Email de contacto principal",
                        max_length=254,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Teléfono de contacto",
                        max_length=20,
                    ),
                ),
                (
                    "max_users",
                    models.PositiveIntegerField(
                        default=50, help_text="Número máximo de usuarios permitidos"
                    ),
                ),
                (
                    "max_markets",
                    models.PositiveIntegerField(
                        default=100, help_text="Número máximo de mercados permitidos"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["slug"], name="idx_org_slug"),
                    models.Index(fields=["is_active"], name="idx_org_active"),
                ],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organización a la que pertenece el usuario",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="users.organization",
            ),
        ),
    ]
