# Generated by Django 5.1.11 on 2025-07-21 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="market",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name="Refrigerator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refrigerators",
                        to="market.market",
                    ),
                ),
            ],
            options={
                "verbose_name": "Refrigerator",
                "verbose_name_plural": "Refrigerators",
                "unique_together": {("market", "name")},
            },
        ),
        migrations.CreateModel(
            name="TemperatureRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("temperature", models.FloatField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "refrigerator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temperature_records",
                        to="market.refrigerator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Temperature Record",
                "verbose_name_plural": "Temperature Records",
                "ordering": ["-date"],
                "unique_together": {("refrigerator", "date")},
            },
        ),
    ]
