# Generated by Django 5.1.11 on 2025-09-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0004_fix_temperature_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="temperaturerecord",
            options={
                "ordering": ["-date", "period"],
                "verbose_name": "Temperature Record",
                "verbose_name_plural": "Temperature Records",
            },
        ),
        migrations.AlterUniqueTogether(
            name="temperaturerecord",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="temperaturerecord",
            name="period",
            field=models.CharField(
                choices=[("MORNING", "Mañana"), ("NIGHT", "Noche")],
                default="MORNING",
                help_text="Período del día para el registro de temperatura",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="temperaturerecord",
            name="temperature",
            field=models.FloatField(help_text="Temperatura en grados Celsius"),
        ),
        migrations.AlterUniqueTogether(
            name="temperaturerecord",
            unique_together={("refrigerator", "date", "period")},
        ),
        migrations.AddConstraint(
            model_name="temperaturerecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("temperature__gte", -30.0), ("temperature__lte", 10.0)
                ),
                name="temperature_range_check",
            ),
        ),
    ]
