# Generated by Django 5.1.11 on 2025-11-04 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_alter_temperaturerecord_options_and_more"),
        ("users", "0003_user_role_organization_user_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organización a la que pertenece el mercado",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="markets",
                to="users.organization",
            ),
        ),
        migrations.AlterField(
            model_name="market",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="market",
            unique_together={("organization", "name")},
        ),
    ]
