# Generated by Django 5.1.11 on 2025-10-30 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceParse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del archivo original"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Archivo PDF de la factura",
                        upload_to="invoices/%Y/%m/%d/",
                        verbose_name="Archivo PDF",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("PROCESSING", "Procesando"),
                            ("COMPLETED", "Completado"),
                            ("FAILED", "Fallido"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "csv_data",
                    models.TextField(
                        blank=True,
                        help_text="CSV completo extraído del PDF",
                        null=True,
                        verbose_name="Datos CSV extraídos",
                    ),
                ),
                (
                    "openai_file_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID de archivo en OpenAI",
                    ),
                ),
                (
                    "openai_response",
                    models.JSONField(
                        blank=True,
                        help_text="Respuesta completa de la API de OpenAI",
                        null=True,
                        verbose_name="Respuesta de OpenAI",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensaje de error"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completado en"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_parses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Subido por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura Parseada",
                "verbose_name_plural": "Facturas Parseadas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line_number",
                    models.PositiveIntegerField(
                        help_text="Orden de la línea en el CSV",
                        verbose_name="Número de línea",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(blank=True, max_length=50, verbose_name="Código"),
                ),
                (
                    "cajas",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Cajas",
                    ),
                ),
                (
                    "uc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="UC (Unidades por caja)",
                    ),
                ),
                (
                    "iva",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="IVA (%)",
                    ),
                ),
                (
                    "articulo",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Artículo"
                    ),
                ),
                (
                    "udes",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Unidades",
                    ),
                ),
                (
                    "unidad",
                    models.CharField(blank=True, max_length=20, verbose_name="Unidad"),
                ),
                (
                    "precio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Precio sin IVA",
                    ),
                ),
                (
                    "precio_iva",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Precio con IVA",
                    ),
                ),
                (
                    "importe",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Importe total",
                    ),
                ),
                (
                    "contenedor",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Contenedor"
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        help_text="Datos originales de la línea del CSV",
                        null=True,
                        verbose_name="Datos sin procesar",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "invoice_parse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="invoice_parser.invoiceparse",
                        verbose_name="Factura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de Factura",
                "verbose_name_plural": "Líneas de Factura",
                "ordering": ["invoice_parse", "line_number"],
            },
        ),
        migrations.AddIndex(
            model_name="invoiceparse",
            index=models.Index(
                fields=["-created_at"], name="invoice_par_created_45606e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoiceparse",
            index=models.Index(
                fields=["uploaded_by", "-created_at"],
                name="invoice_par_uploade_586031_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoiceparse",
            index=models.Index(fields=["status"], name="invoice_par_status_c6cc20_idx"),
        ),
        migrations.AddIndex(
            model_name="invoicelineitem",
            index=models.Index(
                fields=["invoice_parse", "line_number"],
                name="invoice_par_invoice_ded9ec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoicelineitem",
            index=models.Index(fields=["codigo"], name="invoice_par_codigo_93d8ef_idx"),
        ),
        migrations.AddIndex(
            model_name="invoicelineitem",
            index=models.Index(
                fields=["articulo"], name="invoice_par_articul_3868f3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="invoicelineitem",
            unique_together={("invoice_parse", "line_number")},
        ),
    ]
