# Generated by Django 5.1.11 on 2025-10-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice_parser", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoicelineitem",
            name="importe",
        ),
        migrations.RemoveField(
            model_name="invoicelineitem",
            name="iva",
        ),
        migrations.RemoveField(
            model_name="invoicelineitem",
            name="precio",
        ),
        migrations.RemoveField(
            model_name="invoicelineitem",
            name="precio_iva",
        ),
        migrations.RemoveField(
            model_name="invoiceparse",
            name="openai_response",
        ),
        migrations.AddField(
            model_name="invoiceparse",
            name="openai_run_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="ID de run en OpenAI",
            ),
        ),
        migrations.AddField(
            model_name="invoiceparse",
            name="openai_thread_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="ID de thread en OpenAI",
            ),
        ),
        migrations.AlterField(
            model_name="invoicelineitem",
            name="contenedor",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Contenedor"
            ),
        ),
        migrations.AlterField(
            model_name="invoicelineitem",
            name="unidad",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Unidad"
            ),
        ),
    ]
