# Generated by Django 5.1.11 on 2025-10-03 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("market", "0003_alter_temperaturerecord_options_and_more"),
        ("proveedores", "0015_provider_contact_person_provider_email_and_more"),
        ("purchase_orders", "0002_historicalpurchaseorder"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reception",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receptions",
                        to="market.market",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receptions",
                        to="purchase_orders.purchaseorder",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reception",
                "verbose_name_plural": "Receptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReceivedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "barcode_scanned",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Barcode that was scanned when receiving this product",
                        max_length=255,
                    ),
                ),
                (
                    "quantity_received",
                    models.PositiveIntegerField(
                        default=1, help_text="Quantity of units received"
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when product was received",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        help_text="Additional notes about the received product",
                        max_length=500,
                    ),
                ),
                (
                    "is_damaged",
                    models.BooleanField(
                        default=False, help_text="Flag if product was received damaged"
                    ),
                ),
                (
                    "is_missing",
                    models.BooleanField(
                        default=False,
                        help_text="Flag if product was expected but missing",
                    ),
                ),
                (
                    "is_over_received",
                    models.BooleanField(
                        default=False,
                        help_text="Quantity received is greater than ordered for this product",
                    ),
                ),
                (
                    "is_under_received",
                    models.BooleanField(
                        default=False,
                        help_text="Quantity received is less than ordered for this product",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        help_text="Market where the product was received",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_products",
                        to="market.market",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product that was received",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_records",
                        to="proveedores.product",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        help_text="Purchase order this product was received from",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_products",
                        to="purchase_orders.purchaseorder",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who received the product",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reception",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reception batch this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="received.reception",
                    ),
                ),
            ],
            options={
                "verbose_name": "Received Product",
                "verbose_name_plural": "Received Products",
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["purchase_order", "product"], name="idx_rp_po_product"
                    ),
                    models.Index(
                        fields=["purchase_order", "market"], name="idx_rp_po_market"
                    ),
                    models.Index(fields=["barcode_scanned"], name="idx_rp_barcode"),
                    models.Index(fields=["received_at"], name="idx_rp_received_at"),
                    models.Index(fields=["received_by"], name="idx_rp_received_by"),
                ],
            },
        ),
    ]
