# Generated by Django 5.1.11 on 2025-10-03 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_alter_temperaturerecord_options_and_more"),
        ("purchase_orders", "0002_historicalpurchaseorder"),
        ("received", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reception",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("COMPLETED", "Completed")],
                default="DRAFT",
                help_text="Reception status",
                max_length=12,
            ),
        ),
        migrations.AddIndex(
            model_name="reception",
            index=models.Index(
                fields=["purchase_order", "market", "status"],
                name="idx_reception_po_market_status",
            ),
        ),
    ]
