# Generated by Django 5.1.11 on 2025-10-03 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("received", "0002_reception_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reception",
            name="invoice_date",
            field=models.DateField(
                blank=True, help_text="Invoice date (YYYY-MM-DD)", null=True
            ),
        ),
        migrations.AddField(
            model_name="reception",
            name="invoice_image_b64",
            field=models.TextField(
                blank=True, default="", help_text="Base64-encoded image of the invoice"
            ),
        ),
        migrations.AddField(
            model_name="reception",
            name="invoice_time",
            field=models.TimeField(
                blank=True, help_text="Invoice time (HH:MM[:SS])", null=True
            ),
        ),
        migrations.AddField(
            model_name="reception",
            name="invoice_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total amount of the invoice (>= 0)",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
