# Generated by Django 5.1.11 on 2025-10-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("received", "0004_add_extra_product_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reception",
            name="invoice_image_b64",
        ),
        migrations.AddField(
            model_name="reception",
            name="invoice_image",
            field=models.ImageField(
                blank=True,
                help_text="Invoice image file",
                null=True,
                upload_to="invoices/",
            ),
        ),
    ]
