# Generated by Django 5.1.11 on 2025-08-28 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proveedores", "0002_productfavorite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_favorite",
        ),
    ]
