# Generated by Django 5.1.11 on 2025-09-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proveedores", "0003_remove_product_is_favorite"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="purchaseorderitem",
            index=models.Index(
                fields=["order", "product"], name="idx_poi_order_product"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity_units__gt", 0)), name="chk_poi_qty_gt_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)),
                name="chk_poi_unit_price_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderitem",
            constraint=models.UniqueConstraint(
                fields=("order", "product"), name="uq_poi_order_product"
            ),
        ),
    ]
