# Generated by Django 5.1.11 on 2025-09-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proveedores", "0004_purchaseorderitem_idx_poi_order_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="amount_boxes",
            field=models.PositiveIntegerField(
                default=0, help_text="Boxes purchased in the last order"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="amount_units",
            field=models.PositiveIntegerField(
                default=0, help_text="Units purchased in the last order"
            ),
        ),
    ]
