# Generated by Django 5.1.11 on 2025-09-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proveedores", "0005_product_amount_boxes_product_amount_units"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stock_units",
        ),
        migrations.RemoveField(
            model_name="product",
            name="units_per_box",
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="purchase_unit",
            field=models.CharField(
                choices=[("units", "units"), ("boxes", "boxes")],
                db_index=True,
                default="units",
                help_text="Unit expressed by the purchaser (no conversion)",
                max_length=10,
            ),
        ),
    ]
