# Generated by Django 5.1.11 on 2025-09-05 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proveedores", "0006_remove_product_stock_units_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="purchaseorderitem",
            name="chk_poi_unit_price_gte_0",
        ),
        migrations.RemoveField(
            model_name="purchaseorderitem",
            name="unit_price",
        ),
    ]
