# Generated by Django 5.1.11 on 2025-09-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "proveedores",
            "0007_remove_purchaseorderitem_chk_poi_unit_price_gte_0_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="purchaseorderitem",
            name="uq_poi_order_product",
        ),
        migrations.AddConstraint(
            model_name="purchaseorderitem",
            constraint=models.UniqueConstraint(
                fields=("order", "product", "purchase_unit"),
                name="uq_poi_order_product_purchase_unit",
            ),
        ),
    ]
