# Generated by Django 5.1.11 on 2025-09-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proveedores", "0008_remove_purchaseorderitem_uq_poi_order_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="units_per_box",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
