# Generated by Django 5.1.11 on 2025-09-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0011_data_units_to_boxes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='purchase_unit',
            field=models.CharField(choices=[('boxes', 'boxes')], db_index=True, default='boxes', help_text='Unit expressed by the purchaser (boxes only)', max_length=10),
        ),
    ]
