# Generated by Django 5.1.11 on 2025-09-25 13:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proveedores", "0012_alter_purchaseorderitem_purchase_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="order_available_weekdays",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Días de la semana que acepta pedidos (0=Lunes, 6=Domingo). Ej: [0,1,2,3,4] para Lun-Vie",
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="order_deadline_time",
            field=models.TimeField(
                default=django.utils.timezone.now,
                help_text="Hora límite para hacer pedidos (ej: 14:30)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalpurchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PLACED", "Placed"),
                    ("RECEIVED", "Received"),
                    ("SHIPPED", "Shipped"),
                    ("CANCELED", "Canceled"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PLACED", "Placed"),
                    ("RECEIVED", "Received"),
                    ("SHIPPED", "Shipped"),
                    ("CANCELED", "Canceled"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=16,
            ),
        ),
    ]
