# Generated by Django 5.1.11 on 2025-10-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proveedores", "0014_remove_purchaseorder_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="contact_person",
            field=models.CharField(
                blank=True, default="", help_text="Persona de contacto", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="email",
            field=models.EmailField(
                blank=True, default="", help_text="Email de contacto", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="phone",
            field=models.CharField(
                blank=True, default="", help_text="Teléfono de contacto", max_length=20
            ),
        ),
    ]
