# Generated by Django 5.1.11 on 2025-11-04 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proveedores", "0015_provider_contact_person_provider_email_and_more"),
        ("users", "0003_user_role_organization_user_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproduct",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Organización a la que pertenece el producto",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organización a la que pertenece el producto",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organización a la que pertenece el proveedor",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="providers",
                to="users.organization",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="sku",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="provider",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("organization", "sku")},
        ),
        migrations.AlterUniqueTogether(
            name="provider",
            unique_together={("organization", "name")},
        ),
    ]
