# Generated by Django 5.1.11 on 2025-10-07 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_alter_temperaturerecord_options_and_more"),
        ("proveedores", "0015_provider_contact_person_provider_email_and_more"),
        ("purchase_orders", "0002_historicalpurchaseorder"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpurchaseorder",
            name="market",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="market.market",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="market",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="market.market",
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(fields=["market"], name="idx_po_market"),
        ),
    ]
