# Generated by Django 5.1.11 on 2025-10-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "purchase_orders",
            "0003_historicalpurchaseorder_market_purchaseorder_market_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpurchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PLACED", "Placed"),
                    ("IN_PROCESS", "In process"),
                    ("RECEIVED", "Received"),
                    ("SHIPPED", "Shipped"),
                    ("CANCELED", "Canceled"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PLACED", "Placed"),
                    ("IN_PROCESS", "In process"),
                    ("RECEIVED", "Received"),
                    ("SHIPPED", "Shipped"),
                    ("CANCELED", "Canceled"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=16,
            ),
        ),
    ]
